function out = featset_name(i)
    % featureset names
    fn = {'all-features', 'triplet', 'triplet-extra', 'sequence', ...
          'structure', 'triplet+extra', 'not-sequence', 'seq+struct', ...
          'not-structure', 'not-triplet', 'extra+str', 'extra+sequence', ...
          'triplet+structure', 'triplet+sequence', 'not-extra' };
    out = fn{i};
end